packages:
  - packages/*

overrides:
  '@ghentcdh/create-crouton': link:packages/create-crouton

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  nx: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx

onlyBuiltDependencies:
  - '@scarf/scarf'
